export const conversations = [
  {
    id: 'c1',
    name: 'Pasteur Jean-Marc',
    role: 'Pasteur Principal',
    avatar: 'JM',
    color: 'from-amber-500 to-orange-600',
    lastMessage: 'Que la paix du Seigneur soit avec vous ce matin.',
    time: '08:42',
    unread: 2,
    online: true,
    type: 'private',
  },
  {
    id: 'c2',
    name: 'Groupe de Prière du Mercredi',
    role: '12 membres',
    avatar: 'GP',
    color: 'from-blue-500 to-indigo-600',
    lastMessage: 'Marie : Je prie pour la guérison de ma mère.',
    time: '07:15',
    unread: 5,
    online: false,
    type: 'group',
  },
  {
    id: 'c3',
    name: 'Ministère des Louanges',
    role: '8 membres',
    avatar: 'ML',
    color: 'from-emerald-500 to-teal-600',
    lastMessage: 'David : La répétition est reportée à 18h.',
    time: 'Hier',
    unread: 0,
    online: false,
    type: 'group',
  },
  {
    id: 'c4',
    name: 'Sophie Martin',
    role: 'Membre',
    avatar: 'SM',
    color: 'from-rose-500 to-pink-600',
    lastMessage: "Merci pour le verset d'aujourd'hui, très touchant 🙏",
    time: 'Hier',
    unread: 0,
    online: true,
    type: 'private',
  },
  {
    id: 'c5',
    name: 'Groupe Jeunesse',
    role: '24 membres',
    avatar: 'GJ',
    color: 'from-violet-500 to-purple-600',
    lastMessage: 'Lucas : Qui sera là vendredi soir ?',
    time: 'Lun',
    unread: 1,
    online: false,
    type: 'group',
  },
  {
    id: 'c6',
    name: 'Thomas Dubois',
    role: 'Diacre',
    avatar: 'TD',
    color: 'from-cyan-500 to-blue-600',
    lastMessage: 'J\'ai préparé le planning du service de dimanche.',
    time: 'Dim',
    unread: 0,
    online: false,
    type: 'private',
  },
]

export const messagesByConversation = {
  c1: [
    { id: 'm1', sender: 'them', text: 'Bonjour frère, comment allez-vous aujourd\'hui ?', time: '08:30' },
    { id: 'm2', sender: 'me', text: 'Très bien pasteur, grâce à Dieu. Et vous ?', time: '08:35' },
    { id: 'm3', sender: 'them', text: 'Je vais bien, merci. J\'ai pensé à vous pendant ma prière ce matin.', time: '08:40' },
    { id: 'm4', sender: 'them', text: 'Que la paix du Seigneur soit avec vous ce matin.', time: '08:42' },
  ],
  c2: [
    { id: 'm1', sender: 'them', name: 'Marie', text: 'Bonjour à tous, je prie pour la guérison de ma mère ce matin.', time: '07:10' },
    { id: 'm2', sender: 'them', name: 'Pierre', text: 'Nous prions avec toi Marie. Que Dieu la restaure.', time: '07:12' },
    { id: 'm3', sender: 'me', text: 'Amen. Je joins mes prières aux vôtres.', time: '07:14' },
    { id: 'm4', sender: 'them', name: 'Marie', text: 'Merci beaucoup, ça me touche profondément.', time: '07:15' },
  ],
  c3: [
    { id: 'm1', sender: 'them', name: 'David', text: 'La répétition est reportée à 18h ce soir.', time: '19:02' },
    { id: 'm2', sender: 'me', text: 'Parfait, je serai là à 18h pile.', time: '19:05' },
  ],
  c4: [
    { id: 'm1', sender: 'them', text: 'Merci pour le verset d\'aujourd\'hui, très touchant 🙏', time: '20:15' },
    { id: 'm2', sender: 'me', text: 'C\'est un plaisir Sophie, il m\'a beaucoup parlé aussi.', time: '20:20' },
  ],
  c5: [
    { id: 'm1', sender: 'them', name: 'Lucas', text: 'Qui sera là vendredi soir pour la soirée louange ?', time: '17:30' },
    { id: 'm2', sender: 'me', text: 'Je serai là !', time: '17:45' },
  ],
  c6: [
    { id: 'm1', sender: 'them', text: 'J\'ai préparé le planning du service de dimanche.', time: '14:00' },
    { id: 'm2', sender: 'me', text: 'Super, merci Thomas. Je regarde ça.', time: '14:10' },
  ],
}

export const announcements = [
  {
    id: 'a1',
    author: 'Pasteur Jean-Marc',
    role: 'Pasteur Principal',
    avatar: 'JM',
    time: 'Il y a 30 min',
    type: 'announcement',
    content: 'Bien-aimés, ce dimanche nous aurons le privilège d\'accueillir la famille Dupont pour leur baptême. Réjouissons-nous ensemble pour cette nouvelle vie en Christ !',
    reactions: { '🙏': 24, '❤️': 18, '🙌': 12 },
  },
  {
    id: 'a2',
    author: 'Verset du Jour',
    role: 'Écriture Sainte',
    avatar: 'VD',
    time: 'Il y a 2 h',
    type: 'verse',
    reference: 'Philippiens 4:13',
    content: 'Je puis tout par celui qui me fortifie.',
    reactions: { '🙏': 56, '❤️': 42, '🔥': 9 },
  },
  {
    id: 'a3',
    author: 'Église Évangélique de la Grâce',
    role: 'Événement à venir',
    avatar: 'EV',
    time: 'Hier',
    type: 'event',
    title: 'Veillée de Prière & Adoration',
    date: 'Vendredi 8 Août · 20h00',
    location: 'Temple Central · 12 Rue de la Foi',
    content: 'Une soirée de louange, d\'adoration et de prière communautaire. Venez comme vous êtes, Dieu vous attend.',
    reactions: { '🙌': 31, '🙏': 22, '❤️': 15 },
  },
  {
    id: 'a4',
    author: 'Pasteur Jean-Marc',
    role: 'Pasteur Principal',
    avatar: 'JM',
    time: 'Lun',
    type: 'announcement',
    content: 'Rappel : les inscriptions pour le camp des jeunes sont ouvertes jusqu\'au 15 août. Ne tardez pas, les places sont limitées à 40 participants.',
    reactions: { '🙏': 14, '❤️': 8 },
  },
  {
    id: 'a5',
    author: 'Verset du Jour',
    role: 'Écriture Sainte',
    avatar: 'VD',
    time: 'Lun',
    type: 'verse',
    reference: 'Psaume 23:1',
    content: 'L\'Éternel est mon berger : je ne manquerai de rien.',
    reactions: { '🙏': 68, '❤️': 51, '🙌': 20 },
  },
]

export const userProfile = {
  name: 'Daniel Lefèvre',
  email: 'daniel.lefevre@email.com',
  church: 'Église Évangélique de la Grâce',
  role: 'Membre actif · Ministère d\'Accueil',
  avatar: 'DL',
  memberSince: 'Membre depuis 2019',
  stats: {
    events: 47,
    prayers: 128,
    donations: 15,
  },
}
